services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-clean-project-app
    restart: always
    ports:
      - "${LOCAL_SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  # Database Service (MySQL)
  mysql:
    image: mysql:8.0.37
    container_name: go-clean-project-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${LOCAL_MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Service
  redis:
    image: redis:7.2.4-alpine
    container_name: go-clean-project-redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "${LOCAL_REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: go-clean-project-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana
  grafana:
    image: grafana/grafana:10.1.5
    container_name: go-clean-project-grafana
    restart: always
    ports:
      - "3000:3000"

volumes:
  mysql_data:
  redis_data:

